[build-system]
requires = ["setuptools>=61.0", "cmake", "pybind11", "nanobind", "wheel", "pip", "ninja"]
build-backend = "setuptools.build_meta"

[project]
name = "ttir_builder"
description = "Python Endpoint to write TTIR dialect graphs"
authors = [
  { name = "Tenstorrent", email = "info@tenstorrent.com" }
]
requires-python = ">=3.8"
keywords = ["tt-mlir", "ttir", "dialect", "machine learning", "tenstorrent"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

dynamic = ["dependencies", "version", "readme"]

[project.urls]
Homepage = "https://docs.tenstorrent.com/tt-mlir/"
Documentation = "https://docs.tenstorrent.com/tt-mlir/ttir-builder.html"
Repository = "https://github.com/tenstorrent/tt-mlir"
Issues = "https://github.com/tenstorrent/tt-mlir/issues"

[tool.cibuildwheel]
build = "cp310-manylinux_x86_64*"
skip = "*-musllinux_*"
environment = { IN_CIBW_ENV = "ON" }
build-verbosity = 2

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "ghcr.io/tenstorrent/tt-mlir/tt-mlir-manylinux-2-34"
