// SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#ifndef PYTHON_BINDINGS_TTMLIR_SDYENUMS
#define PYTHON_BINDINGS_TTMLIR_SDYENUMS

//include "ttmlir/Dialect/TTCore/IR/TTCoreOps.td"
//include "/opt/ttmlir-toolchain/src/shardy/shardy/dialect/sdy/ir/enums.td"
include "shardy/dialect/sdy/ir/dialect.td"
include "shardy/dialect/sdy/ir/ops.td"
include "shardy/dialect/sdy/ir/enums.td"
include "shardy/dialect/sdy/ir/op_interface.td"


#endif
