name: On Nightly

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

permissions:
  checks: write
  packages: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  build-and-test:
    needs:
      - pre-commit
      - spdx
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit

  check-all-green:
    if: always()
    needs:
    - pre-commit
    - spdx
    - build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Check if the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: build-and-test
        jobs: ${{ toJSON(needs) }}

  release-wheel:
    name: "Release the tt-torch wheel"
    # todo(vvukoman): before merging uncomment this
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - check-all-green
      - build-and-test
    steps:
      - name: Tag and release
        # todo(vvukoman): before merging switch to @main
        uses: tenstorrent/tt-forge/.github/actions/tag-and-release@vvukoman/tag-and-release-action
        with:
          wheel-artifact-name: ${{ needs.build-and-test.outputs.wheel-artifact-name }}
          untar-wheel-artifact: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
