name: On push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  build-and-test:
    needs:
      - pre-commit
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
