name: On PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  macos-build:
    uses: ./.github/workflows/macos-build.yml
    secrets: inherit
  build-and-test-debug:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      config: 'debug'
  build-and-test-release:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      config: 'release'
