name: On PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-skip-check:
    runs-on: ubuntu-latest
    name: pr-skip-check
    outputs:
      output: ${{ steps.skip.outputs.output }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v45
        id: changed-files
      - name: check
        shell: bash
        env:
          changed_files: ${{ toJson(steps.changed-files.outputs) }}
          pull_request: ${{ toJson(github.event.pull_request) }}
        id: skip
        run: |
          echo "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
          python .github/scripts/pr.py
          cat "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: 
      - pr-skip-check
    name: Test
    steps:
      - name: check
        shell: bash
        run: |
          echo ${{ fromJson(needs.pr-skip-check.outputs.output) }}
      
