name: On PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  macos-build:
    uses: ./.github/workflows/macos-build.yml
    secrets: inherit
  build-ci-image:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  build-ird-debug-image:
    needs: build-ci-image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      config: 'debug'
  build-and-test-debug:
    needs: build-ci-image
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      config: 'Debug'
  build-and-test-release:
    needs: build-ci-image
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      config: 'Release'
