name: On PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    runs-on: ubuntu-latest
    name: pr-check
    outputs:
      results: ${{ steps.script.outputs.results }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v45
        id: changed-files
      - name: check
        shell: bash
        env:
          changed_files: ${{ toJson(steps.changed-files.outputs) }}
          pull_request: ${{ toJson(github.event.pull_request) }}
          job_name: ${{ github.job }}
        id: script
        run: |
          echo $job_name
          python .github/scripts/pr.py

  test:
    runs-on: ubuntu-latest
    needs: 
      - pr-check
    name: Test
    if: ${{ fromJson(needs.pr-skip-check.outputs.results).test.skip  == false }}
    steps:
      - name: check
        shell: bash
        run: |
          echo ${{ fromJson(needs.pr-skip-check.outputs.results).test.skip }}
      
